/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as HermesRouteImport } from './routes/hermes'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LiveRouteImport } from './routes/live'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ValidatorRouteImport } from './routes/validator'
import { Route as ApiHermesAccountsRouteImport } from './routes/api/hermes/accounts'
import { Route as ApiHermesBacktestsRouteImport } from './routes/api/hermes/backtests'
import { Route as ApiHermesJournalRouteImport } from './routes/api/hermes/journal'
import { Route as ApiHermesKnowledgeRouteImport } from './routes/api/hermes/knowledge'
import { Route as ApiHermesNotesRouteImport } from './routes/api/hermes/notes'
import { Route as ApiHermesRequestsRouteImport } from './routes/api/hermes/requests'
import { Route as ApiHermesSetupsRouteImport } from './routes/api/hermes/setups'
import { Route as ApiHermesUnderstandingRouteImport } from './routes/api/hermes/understanding'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const HermesRoute = HermesRouteImport.update({
  id: '/hermes',
  path: '/hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidatorRoute = ValidatorRouteImport.update({
  id: '/validator',
  path: '/validator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesAccountsRoute = ApiHermesAccountsRouteImport.update({
  id: '/api/hermes/accounts',
  path: '/api/hermes/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesBacktestsRoute = ApiHermesBacktestsRouteImport.update({
  id: '/api/hermes/backtests',
  path: '/api/hermes/backtests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesJournalRoute = ApiHermesJournalRouteImport.update({
  id: '/api/hermes/journal',
  path: '/api/hermes/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesKnowledgeRoute = ApiHermesKnowledgeRouteImport.update({
  id: '/api/hermes/knowledge',
  path: '/api/hermes/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesNotesRoute = ApiHermesNotesRouteImport.update({
  id: '/api/hermes/notes',
  path: '/api/hermes/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesRequestsRoute = ApiHermesRequestsRouteImport.update({
  id: '/api/hermes/requests',
  path: '/api/hermes/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesSetupsRoute = ApiHermesSetupsRouteImport.update({
  id: '/api/hermes/setups',
  path: '/api/hermes/setups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesUnderstandingRoute = ApiHermesUnderstandingRouteImport.update({
  id: '/api/hermes/understanding',
  path: '/api/hermes/understanding',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/hermes': typeof HermesRoute
  '/journal': typeof JournalRoute
  '/live': typeof LiveRoute
  '/settings': typeof SettingsRoute
  '/validator': typeof ValidatorRoute
  '/api/hermes/accounts': typeof ApiHermesAccountsRoute
  '/api/hermes/backtests': typeof ApiHermesBacktestsRoute
  '/api/hermes/journal': typeof ApiHermesJournalRoute
  '/api/hermes/knowledge': typeof ApiHermesKnowledgeRoute
  '/api/hermes/notes': typeof ApiHermesNotesRoute
  '/api/hermes/requests': typeof ApiHermesRequestsRoute
  '/api/hermes/setups': typeof ApiHermesSetupsRoute
  '/api/hermes/understanding': typeof ApiHermesUnderstandingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/hermes': typeof HermesRoute
  '/journal': typeof JournalRoute
  '/live': typeof LiveRoute
  '/settings': typeof SettingsRoute
  '/validator': typeof ValidatorRoute
  '/api/hermes/accounts': typeof ApiHermesAccountsRoute
  '/api/hermes/backtests': typeof ApiHermesBacktestsRoute
  '/api/hermes/journal': typeof ApiHermesJournalRoute
  '/api/hermes/knowledge': typeof ApiHermesKnowledgeRoute
  '/api/hermes/notes': typeof ApiHermesNotesRoute
  '/api/hermes/requests': typeof ApiHermesRequestsRoute
  '/api/hermes/setups': typeof ApiHermesSetupsRoute
  '/api/hermes/understanding': typeof ApiHermesUnderstandingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/hermes': typeof HermesRoute
  '/journal': typeof JournalRoute
  '/live': typeof LiveRoute
  '/settings': typeof SettingsRoute
  '/validator': typeof ValidatorRoute
  '/api/hermes/accounts': typeof ApiHermesAccountsRoute
  '/api/hermes/backtests': typeof ApiHermesBacktestsRoute
  '/api/hermes/journal': typeof ApiHermesJournalRoute
  '/api/hermes/knowledge': typeof ApiHermesKnowledgeRoute
  '/api/hermes/notes': typeof ApiHermesNotesRoute
  '/api/hermes/requests': typeof ApiHermesRequestsRoute
  '/api/hermes/setups': typeof ApiHermesSetupsRoute
  '/api/hermes/understanding': typeof ApiHermesUnderstandingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/hermes'
    | '/journal'
    | '/live'
    | '/settings'
    | '/validator'
    | '/api/hermes/accounts'
    | '/api/hermes/backtests'
    | '/api/hermes/journal'
    | '/api/hermes/knowledge'
    | '/api/hermes/notes'
    | '/api/hermes/requests'
    | '/api/hermes/setups'
    | '/api/hermes/understanding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/hermes'
    | '/journal'
    | '/live'
    | '/settings'
    | '/validator'
    | '/api/hermes/accounts'
    | '/api/hermes/backtests'
    | '/api/hermes/journal'
    | '/api/hermes/knowledge'
    | '/api/hermes/notes'
    | '/api/hermes/requests'
    | '/api/hermes/setups'
    | '/api/hermes/understanding'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/hermes'
    | '/journal'
    | '/live'
    | '/settings'
    | '/validator'
    | '/api/hermes/accounts'
    | '/api/hermes/backtests'
    | '/api/hermes/journal'
    | '/api/hermes/knowledge'
    | '/api/hermes/notes'
    | '/api/hermes/requests'
    | '/api/hermes/setups'
    | '/api/hermes/understanding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  HermesRoute: typeof HermesRoute
  JournalRoute: typeof JournalRoute
  LiveRoute: typeof LiveRoute
  SettingsRoute: typeof SettingsRoute
  ValidatorRoute: typeof ValidatorRoute
  ApiHermesAccountsRoute: typeof ApiHermesAccountsRoute
  ApiHermesBacktestsRoute: typeof ApiHermesBacktestsRoute
  ApiHermesJournalRoute: typeof ApiHermesJournalRoute
  ApiHermesKnowledgeRoute: typeof ApiHermesKnowledgeRoute
  ApiHermesNotesRoute: typeof ApiHermesNotesRoute
  ApiHermesRequestsRoute: typeof ApiHermesRequestsRoute
  ApiHermesSetupsRoute: typeof ApiHermesSetupsRoute
  ApiHermesUnderstandingRoute: typeof ApiHermesUnderstandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hermes': {
      id: '/hermes'
      path: '/hermes'
      fullPath: '/hermes'
      preLoaderRoute: typeof HermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validator': {
      id: '/validator'
      path: '/validator'
      fullPath: '/validator'
      preLoaderRoute: typeof ValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/accounts': {
      id: '/api/hermes/accounts'
      path: '/api/hermes/accounts'
      fullPath: '/api/hermes/accounts'
      preLoaderRoute: typeof ApiHermesAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/backtests': {
      id: '/api/hermes/backtests'
      path: '/api/hermes/backtests'
      fullPath: '/api/hermes/backtests'
      preLoaderRoute: typeof ApiHermesBacktestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/journal': {
      id: '/api/hermes/journal'
      path: '/api/hermes/journal'
      fullPath: '/api/hermes/journal'
      preLoaderRoute: typeof ApiHermesJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/knowledge': {
      id: '/api/hermes/knowledge'
      path: '/api/hermes/knowledge'
      fullPath: '/api/hermes/knowledge'
      preLoaderRoute: typeof ApiHermesKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/notes': {
      id: '/api/hermes/notes'
      path: '/api/hermes/notes'
      fullPath: '/api/hermes/notes'
      preLoaderRoute: typeof ApiHermesNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/requests': {
      id: '/api/hermes/requests'
      path: '/api/hermes/requests'
      fullPath: '/api/hermes/requests'
      preLoaderRoute: typeof ApiHermesRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/setups': {
      id: '/api/hermes/setups'
      path: '/api/hermes/setups'
      fullPath: '/api/hermes/setups'
      preLoaderRoute: typeof ApiHermesSetupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/understanding': {
      id: '/api/hermes/understanding'
      path: '/api/hermes/understanding'
      fullPath: '/api/hermes/understanding'
      preLoaderRoute: typeof ApiHermesUnderstandingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  HermesRoute: HermesRoute,
  JournalRoute: JournalRoute,
  LiveRoute: LiveRoute,
  SettingsRoute: SettingsRoute,
  ValidatorRoute: ValidatorRoute,
  ApiHermesAccountsRoute: ApiHermesAccountsRoute,
  ApiHermesBacktestsRoute: ApiHermesBacktestsRoute,
  ApiHermesJournalRoute: ApiHermesJournalRoute,
  ApiHermesKnowledgeRoute: ApiHermesKnowledgeRoute,
  ApiHermesNotesRoute: ApiHermesNotesRoute,
  ApiHermesRequestsRoute: ApiHermesRequestsRoute,
  ApiHermesSetupsRoute: ApiHermesSetupsRoute,
  ApiHermesUnderstandingRoute: ApiHermesUnderstandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
