/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HermesRouteImport } from './routes/hermes'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PnlRouteImport } from './routes/pnl'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SmcRouteImport } from './routes/smc'
import { Route as ValidatorRouteImport } from './routes/validator'
import { Route as ApiEconomicEventsRouteImport } from './routes/api/economic-events'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiFinnhub_webhookRouteImport } from './routes/api/finnhub_webhook'
import { Route as ApiOhlcvRouteImport } from './routes/api/ohlcv'
import { Route as ApiSmcRouteImport } from './routes/api/smc'
import { Route as ApiSmcAnalyzeRouteImport } from './routes/api/smc-analyze'
import { Route as ApiSmcMigrateRouteImport } from './routes/api/smc-migrate'
import { Route as ApiSmcMigrateChatRouteImport } from './routes/api/smc-migrate-chat'
import { Route as ApiSmcStrategyConfigRouteImport } from './routes/api/smc-strategy-config'
import { Route as ApiStrategiesRouteImport } from './routes/api/strategies'
import { Route as ApiHermesDebugRouteImport } from './routes/api/hermes/_debug'
import { Route as ApiHermesAccountsRouteImport } from './routes/api/hermes/accounts'
import { Route as ApiHermesAnalysisRouteImport } from './routes/api/hermes/analysis'
import { Route as ApiHermesAnalyzeNewsRouteImport } from './routes/api/hermes/analyze-news'
import { Route as ApiHermesAnalyzeWithHermesRouteImport } from './routes/api/hermes/analyze-with-hermes'
import { Route as ApiHermesBacktestsRouteImport } from './routes/api/hermes/backtests'
import { Route as ApiHermesJournalRouteImport } from './routes/api/hermes/journal'
import { Route as ApiHermesKnowledgeRouteImport } from './routes/api/hermes/knowledge'
import { Route as ApiHermesNotesRouteImport } from './routes/api/hermes/notes'
import { Route as ApiHermesOutcomesRouteImport } from './routes/api/hermes/outcomes'
import { Route as ApiHermesPineScriptAnalysisRouteImport } from './routes/api/hermes/pine-script-analysis'
import { Route as ApiHermesRequestsRouteImport } from './routes/api/hermes/requests'
import { Route as ApiHermesSetupsRouteImport } from './routes/api/hermes/setups'
import { Route as ApiHermesSmcChatRouteImport } from './routes/api/hermes/smc-chat'
import { Route as ApiHermesSmcScreenshotsRouteImport } from './routes/api/hermes/smc-screenshots'
import { Route as ApiHermesSmcStatusRouteImport } from './routes/api/hermes/smc-status'
import { Route as ApiHermesSmcUpgradeChatRouteImport } from './routes/api/hermes/smc-upgrade-chat'
import { Route as ApiHermesSmcUpgradeConfigRouteImport } from './routes/api/hermes/smc-upgrade-config'
import { Route as ApiHermesStrategyAnalysisRouteImport } from './routes/api/hermes/strategy-analysis'
import { Route as ApiHermesStrategyRulesRouteImport } from './routes/api/hermes/strategy-rules'
import { Route as ApiHermesUnderstandingRouteImport } from './routes/api/hermes/understanding'
import { Route as ApiHermesUserStrategiesRouteImport } from './routes/api/hermes/user-strategies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HermesRoute = HermesRouteImport.update({
  id: '/hermes',
  path: '/hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PnlRoute = PnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SmcRoute = SmcRouteImport.update({
  id: '/smc',
  path: '/smc',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidatorRoute = ValidatorRouteImport.update({
  id: '/validator',
  path: '/validator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEconomicEventsRoute = ApiEconomicEventsRouteImport.update({
  id: '/api/economic-events',
  path: '/api/economic-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinnhub_webhookRoute = ApiFinnhub_webhookRouteImport.update({
  id: '/api/finnhub_webhook',
  path: '/api/finnhub_webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOhlcvRoute = ApiOhlcvRouteImport.update({
  id: '/api/ohlcv',
  path: '/api/ohlcv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmcRoute = ApiSmcRouteImport.update({
  id: '/api/smc',
  path: '/api/smc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmcAnalyzeRoute = ApiSmcAnalyzeRouteImport.update({
  id: '/api/smc-analyze',
  path: '/api/smc-analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmcMigrateRoute = ApiSmcMigrateRouteImport.update({
  id: '/api/smc-migrate',
  path: '/api/smc-migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmcMigrateChatRoute = ApiSmcMigrateChatRouteImport.update({
  id: '/api/smc-migrate-chat',
  path: '/api/smc-migrate-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmcStrategyConfigRoute = ApiSmcStrategyConfigRouteImport.update({
  id: '/api/smc-strategy-config',
  path: '/api/smc-strategy-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStrategiesRoute = ApiStrategiesRouteImport.update({
  id: '/api/strategies',
  path: '/api/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesDebugRoute = ApiHermesDebugRouteImport.update({
  id: '/api/hermes/_debug',
  path: '/api/hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesAccountsRoute = ApiHermesAccountsRouteImport.update({
  id: '/api/hermes/accounts',
  path: '/api/hermes/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesAnalysisRoute = ApiHermesAnalysisRouteImport.update({
  id: '/api/hermes/analysis',
  path: '/api/hermes/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesAnalyzeNewsRoute = ApiHermesAnalyzeNewsRouteImport.update({
  id: '/api/hermes/analyze-news',
  path: '/api/hermes/analyze-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesAnalyzeWithHermesRoute =
  ApiHermesAnalyzeWithHermesRouteImport.update({
    id: '/api/hermes/analyze-with-hermes',
    path: '/api/hermes/analyze-with-hermes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHermesBacktestsRoute = ApiHermesBacktestsRouteImport.update({
  id: '/api/hermes/backtests',
  path: '/api/hermes/backtests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesJournalRoute = ApiHermesJournalRouteImport.update({
  id: '/api/hermes/journal',
  path: '/api/hermes/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesKnowledgeRoute = ApiHermesKnowledgeRouteImport.update({
  id: '/api/hermes/knowledge',
  path: '/api/hermes/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesNotesRoute = ApiHermesNotesRouteImport.update({
  id: '/api/hermes/notes',
  path: '/api/hermes/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesOutcomesRoute = ApiHermesOutcomesRouteImport.update({
  id: '/api/hermes/outcomes',
  path: '/api/hermes/outcomes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesPineScriptAnalysisRoute =
  ApiHermesPineScriptAnalysisRouteImport.update({
    id: '/api/hermes/pine-script-analysis',
    path: '/api/hermes/pine-script-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHermesRequestsRoute = ApiHermesRequestsRouteImport.update({
  id: '/api/hermes/requests',
  path: '/api/hermes/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesSetupsRoute = ApiHermesSetupsRouteImport.update({
  id: '/api/hermes/setups',
  path: '/api/hermes/setups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesSmcChatRoute = ApiHermesSmcChatRouteImport.update({
  id: '/api/hermes/smc-chat',
  path: '/api/hermes/smc-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesSmcScreenshotsRoute = ApiHermesSmcScreenshotsRouteImport.update({
  id: '/api/hermes/smc-screenshots',
  path: '/api/hermes/smc-screenshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesSmcStatusRoute = ApiHermesSmcStatusRouteImport.update({
  id: '/api/hermes/smc-status',
  path: '/api/hermes/smc-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesSmcUpgradeChatRoute = ApiHermesSmcUpgradeChatRouteImport.update({
  id: '/api/hermes/smc-upgrade-chat',
  path: '/api/hermes/smc-upgrade-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesSmcUpgradeConfigRoute =
  ApiHermesSmcUpgradeConfigRouteImport.update({
    id: '/api/hermes/smc-upgrade-config',
    path: '/api/hermes/smc-upgrade-config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHermesStrategyAnalysisRoute =
  ApiHermesStrategyAnalysisRouteImport.update({
    id: '/api/hermes/strategy-analysis',
    path: '/api/hermes/strategy-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHermesStrategyRulesRoute = ApiHermesStrategyRulesRouteImport.update({
  id: '/api/hermes/strategy-rules',
  path: '/api/hermes/strategy-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesUnderstandingRoute = ApiHermesUnderstandingRouteImport.update({
  id: '/api/hermes/understanding',
  path: '/api/hermes/understanding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesUserStrategiesRoute = ApiHermesUserStrategiesRouteImport.update({
  id: '/api/hermes/user-strategies',
  path: '/api/hermes/user-strategies',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/backtest': typeof BacktestRoute
  '/briefing': typeof BriefingRoute
  '/calendar': typeof CalendarRoute
  '/console': typeof ConsoleRoute
  '/help': typeof HelpRoute
  '/hermes': typeof HermesRoute
  '/journal': typeof JournalRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/pnl': typeof PnlRoute
  '/settings': typeof SettingsRoute
  '/smc': typeof SmcRoute
  '/validator': typeof ValidatorRoute
  '/api/economic-events': typeof ApiEconomicEventsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/finnhub_webhook': typeof ApiFinnhub_webhookRoute
  '/api/ohlcv': typeof ApiOhlcvRoute
  '/api/smc': typeof ApiSmcRoute
  '/api/smc-analyze': typeof ApiSmcAnalyzeRoute
  '/api/smc-migrate': typeof ApiSmcMigrateRoute
  '/api/smc-migrate-chat': typeof ApiSmcMigrateChatRoute
  '/api/smc-strategy-config': typeof ApiSmcStrategyConfigRoute
  '/api/strategies': typeof ApiStrategiesRoute
  '/api/hermes': typeof ApiHermesDebugRoute
  '/api/hermes/accounts': typeof ApiHermesAccountsRoute
  '/api/hermes/analysis': typeof ApiHermesAnalysisRoute
  '/api/hermes/analyze-news': typeof ApiHermesAnalyzeNewsRoute
  '/api/hermes/analyze-with-hermes': typeof ApiHermesAnalyzeWithHermesRoute
  '/api/hermes/backtests': typeof ApiHermesBacktestsRoute
  '/api/hermes/journal': typeof ApiHermesJournalRoute
  '/api/hermes/knowledge': typeof ApiHermesKnowledgeRoute
  '/api/hermes/notes': typeof ApiHermesNotesRoute
  '/api/hermes/outcomes': typeof ApiHermesOutcomesRoute
  '/api/hermes/pine-script-analysis': typeof ApiHermesPineScriptAnalysisRoute
  '/api/hermes/requests': typeof ApiHermesRequestsRoute
  '/api/hermes/setups': typeof ApiHermesSetupsRoute
  '/api/hermes/smc-chat': typeof ApiHermesSmcChatRoute
  '/api/hermes/smc-screenshots': typeof ApiHermesSmcScreenshotsRoute
  '/api/hermes/smc-status': typeof ApiHermesSmcStatusRoute
  '/api/hermes/smc-upgrade-chat': typeof ApiHermesSmcUpgradeChatRoute
  '/api/hermes/smc-upgrade-config': typeof ApiHermesSmcUpgradeConfigRoute
  '/api/hermes/strategy-analysis': typeof ApiHermesStrategyAnalysisRoute
  '/api/hermes/strategy-rules': typeof ApiHermesStrategyRulesRoute
  '/api/hermes/understanding': typeof ApiHermesUnderstandingRoute
  '/api/hermes/user-strategies': typeof ApiHermesUserStrategiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/backtest': typeof BacktestRoute
  '/briefing': typeof BriefingRoute
  '/calendar': typeof CalendarRoute
  '/console': typeof ConsoleRoute
  '/help': typeof HelpRoute
  '/hermes': typeof HermesRoute
  '/journal': typeof JournalRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/pnl': typeof PnlRoute
  '/settings': typeof SettingsRoute
  '/smc': typeof SmcRoute
  '/validator': typeof ValidatorRoute
  '/api/economic-events': typeof ApiEconomicEventsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/finnhub_webhook': typeof ApiFinnhub_webhookRoute
  '/api/ohlcv': typeof ApiOhlcvRoute
  '/api/smc': typeof ApiSmcRoute
  '/api/smc-analyze': typeof ApiSmcAnalyzeRoute
  '/api/smc-migrate': typeof ApiSmcMigrateRoute
  '/api/smc-migrate-chat': typeof ApiSmcMigrateChatRoute
  '/api/smc-strategy-config': typeof ApiSmcStrategyConfigRoute
  '/api/strategies': typeof ApiStrategiesRoute
  '/api/hermes': typeof ApiHermesDebugRoute
  '/api/hermes/accounts': typeof ApiHermesAccountsRoute
  '/api/hermes/analysis': typeof ApiHermesAnalysisRoute
  '/api/hermes/analyze-news': typeof ApiHermesAnalyzeNewsRoute
  '/api/hermes/analyze-with-hermes': typeof ApiHermesAnalyzeWithHermesRoute
  '/api/hermes/backtests': typeof ApiHermesBacktestsRoute
  '/api/hermes/journal': typeof ApiHermesJournalRoute
  '/api/hermes/knowledge': typeof ApiHermesKnowledgeRoute
  '/api/hermes/notes': typeof ApiHermesNotesRoute
  '/api/hermes/outcomes': typeof ApiHermesOutcomesRoute
  '/api/hermes/pine-script-analysis': typeof ApiHermesPineScriptAnalysisRoute
  '/api/hermes/requests': typeof ApiHermesRequestsRoute
  '/api/hermes/setups': typeof ApiHermesSetupsRoute
  '/api/hermes/smc-chat': typeof ApiHermesSmcChatRoute
  '/api/hermes/smc-screenshots': typeof ApiHermesSmcScreenshotsRoute
  '/api/hermes/smc-status': typeof ApiHermesSmcStatusRoute
  '/api/hermes/smc-upgrade-chat': typeof ApiHermesSmcUpgradeChatRoute
  '/api/hermes/smc-upgrade-config': typeof ApiHermesSmcUpgradeConfigRoute
  '/api/hermes/strategy-analysis': typeof ApiHermesStrategyAnalysisRoute
  '/api/hermes/strategy-rules': typeof ApiHermesStrategyRulesRoute
  '/api/hermes/understanding': typeof ApiHermesUnderstandingRoute
  '/api/hermes/user-strategies': typeof ApiHermesUserStrategiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/backtest': typeof BacktestRoute
  '/briefing': typeof BriefingRoute
  '/calendar': typeof CalendarRoute
  '/console': typeof ConsoleRoute
  '/help': typeof HelpRoute
  '/hermes': typeof HermesRoute
  '/journal': typeof JournalRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/pnl': typeof PnlRoute
  '/settings': typeof SettingsRoute
  '/smc': typeof SmcRoute
  '/validator': typeof ValidatorRoute
  '/api/economic-events': typeof ApiEconomicEventsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/finnhub_webhook': typeof ApiFinnhub_webhookRoute
  '/api/ohlcv': typeof ApiOhlcvRoute
  '/api/smc': typeof ApiSmcRoute
  '/api/smc-analyze': typeof ApiSmcAnalyzeRoute
  '/api/smc-migrate': typeof ApiSmcMigrateRoute
  '/api/smc-migrate-chat': typeof ApiSmcMigrateChatRoute
  '/api/smc-strategy-config': typeof ApiSmcStrategyConfigRoute
  '/api/strategies': typeof ApiStrategiesRoute
  '/api/hermes/_debug': typeof ApiHermesDebugRoute
  '/api/hermes/accounts': typeof ApiHermesAccountsRoute
  '/api/hermes/analysis': typeof ApiHermesAnalysisRoute
  '/api/hermes/analyze-news': typeof ApiHermesAnalyzeNewsRoute
  '/api/hermes/analyze-with-hermes': typeof ApiHermesAnalyzeWithHermesRoute
  '/api/hermes/backtests': typeof ApiHermesBacktestsRoute
  '/api/hermes/journal': typeof ApiHermesJournalRoute
  '/api/hermes/knowledge': typeof ApiHermesKnowledgeRoute
  '/api/hermes/notes': typeof ApiHermesNotesRoute
  '/api/hermes/outcomes': typeof ApiHermesOutcomesRoute
  '/api/hermes/pine-script-analysis': typeof ApiHermesPineScriptAnalysisRoute
  '/api/hermes/requests': typeof ApiHermesRequestsRoute
  '/api/hermes/setups': typeof ApiHermesSetupsRoute
  '/api/hermes/smc-chat': typeof ApiHermesSmcChatRoute
  '/api/hermes/smc-screenshots': typeof ApiHermesSmcScreenshotsRoute
  '/api/hermes/smc-status': typeof ApiHermesSmcStatusRoute
  '/api/hermes/smc-upgrade-chat': typeof ApiHermesSmcUpgradeChatRoute
  '/api/hermes/smc-upgrade-config': typeof ApiHermesSmcUpgradeConfigRoute
  '/api/hermes/strategy-analysis': typeof ApiHermesStrategyAnalysisRoute
  '/api/hermes/strategy-rules': typeof ApiHermesStrategyRulesRoute
  '/api/hermes/understanding': typeof ApiHermesUnderstandingRoute
  '/api/hermes/user-strategies': typeof ApiHermesUserStrategiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/backtest'
    | '/briefing'
    | '/calendar'
    | '/console'
    | '/help'
    | '/hermes'
    | '/journal'
    | '/live'
    | '/login'
    | '/pnl'
    | '/settings'
    | '/smc'
    | '/validator'
    | '/api/economic-events'
    | '/api/events'
    | '/api/finnhub_webhook'
    | '/api/ohlcv'
    | '/api/smc'
    | '/api/smc-analyze'
    | '/api/smc-migrate'
    | '/api/smc-migrate-chat'
    | '/api/smc-strategy-config'
    | '/api/strategies'
    | '/api/hermes'
    | '/api/hermes/accounts'
    | '/api/hermes/analysis'
    | '/api/hermes/analyze-news'
    | '/api/hermes/analyze-with-hermes'
    | '/api/hermes/backtests'
    | '/api/hermes/journal'
    | '/api/hermes/knowledge'
    | '/api/hermes/notes'
    | '/api/hermes/outcomes'
    | '/api/hermes/pine-script-analysis'
    | '/api/hermes/requests'
    | '/api/hermes/setups'
    | '/api/hermes/smc-chat'
    | '/api/hermes/smc-screenshots'
    | '/api/hermes/smc-status'
    | '/api/hermes/smc-upgrade-chat'
    | '/api/hermes/smc-upgrade-config'
    | '/api/hermes/strategy-analysis'
    | '/api/hermes/strategy-rules'
    | '/api/hermes/understanding'
    | '/api/hermes/user-strategies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/backtest'
    | '/briefing'
    | '/calendar'
    | '/console'
    | '/help'
    | '/hermes'
    | '/journal'
    | '/live'
    | '/login'
    | '/pnl'
    | '/settings'
    | '/smc'
    | '/validator'
    | '/api/economic-events'
    | '/api/events'
    | '/api/finnhub_webhook'
    | '/api/ohlcv'
    | '/api/smc'
    | '/api/smc-analyze'
    | '/api/smc-migrate'
    | '/api/smc-migrate-chat'
    | '/api/smc-strategy-config'
    | '/api/strategies'
    | '/api/hermes'
    | '/api/hermes/accounts'
    | '/api/hermes/analysis'
    | '/api/hermes/analyze-news'
    | '/api/hermes/analyze-with-hermes'
    | '/api/hermes/backtests'
    | '/api/hermes/journal'
    | '/api/hermes/knowledge'
    | '/api/hermes/notes'
    | '/api/hermes/outcomes'
    | '/api/hermes/pine-script-analysis'
    | '/api/hermes/requests'
    | '/api/hermes/setups'
    | '/api/hermes/smc-chat'
    | '/api/hermes/smc-screenshots'
    | '/api/hermes/smc-status'
    | '/api/hermes/smc-upgrade-chat'
    | '/api/hermes/smc-upgrade-config'
    | '/api/hermes/strategy-analysis'
    | '/api/hermes/strategy-rules'
    | '/api/hermes/understanding'
    | '/api/hermes/user-strategies'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/backtest'
    | '/briefing'
    | '/calendar'
    | '/console'
    | '/help'
    | '/hermes'
    | '/journal'
    | '/live'
    | '/login'
    | '/pnl'
    | '/settings'
    | '/smc'
    | '/validator'
    | '/api/economic-events'
    | '/api/events'
    | '/api/finnhub_webhook'
    | '/api/ohlcv'
    | '/api/smc'
    | '/api/smc-analyze'
    | '/api/smc-migrate'
    | '/api/smc-migrate-chat'
    | '/api/smc-strategy-config'
    | '/api/strategies'
    | '/api/hermes/_debug'
    | '/api/hermes/accounts'
    | '/api/hermes/analysis'
    | '/api/hermes/analyze-news'
    | '/api/hermes/analyze-with-hermes'
    | '/api/hermes/backtests'
    | '/api/hermes/journal'
    | '/api/hermes/knowledge'
    | '/api/hermes/notes'
    | '/api/hermes/outcomes'
    | '/api/hermes/pine-script-analysis'
    | '/api/hermes/requests'
    | '/api/hermes/setups'
    | '/api/hermes/smc-chat'
    | '/api/hermes/smc-screenshots'
    | '/api/hermes/smc-status'
    | '/api/hermes/smc-upgrade-chat'
    | '/api/hermes/smc-upgrade-config'
    | '/api/hermes/strategy-analysis'
    | '/api/hermes/strategy-rules'
    | '/api/hermes/understanding'
    | '/api/hermes/user-strategies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  BacktestRoute: typeof BacktestRoute
  BriefingRoute: typeof BriefingRoute
  CalendarRoute: typeof CalendarRoute
  ConsoleRoute: typeof ConsoleRoute
  HelpRoute: typeof HelpRoute
  HermesRoute: typeof HermesRoute
  JournalRoute: typeof JournalRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  PnlRoute: typeof PnlRoute
  SettingsRoute: typeof SettingsRoute
  SmcRoute: typeof SmcRoute
  ValidatorRoute: typeof ValidatorRoute
  ApiEconomicEventsRoute: typeof ApiEconomicEventsRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiFinnhub_webhookRoute: typeof ApiFinnhub_webhookRoute
  ApiOhlcvRoute: typeof ApiOhlcvRoute
  ApiSmcRoute: typeof ApiSmcRoute
  ApiSmcAnalyzeRoute: typeof ApiSmcAnalyzeRoute
  ApiSmcMigrateRoute: typeof ApiSmcMigrateRoute
  ApiSmcMigrateChatRoute: typeof ApiSmcMigrateChatRoute
  ApiSmcStrategyConfigRoute: typeof ApiSmcStrategyConfigRoute
  ApiStrategiesRoute: typeof ApiStrategiesRoute
  ApiHermesDebugRoute: typeof ApiHermesDebugRoute
  ApiHermesAccountsRoute: typeof ApiHermesAccountsRoute
  ApiHermesAnalysisRoute: typeof ApiHermesAnalysisRoute
  ApiHermesAnalyzeNewsRoute: typeof ApiHermesAnalyzeNewsRoute
  ApiHermesAnalyzeWithHermesRoute: typeof ApiHermesAnalyzeWithHermesRoute
  ApiHermesBacktestsRoute: typeof ApiHermesBacktestsRoute
  ApiHermesJournalRoute: typeof ApiHermesJournalRoute
  ApiHermesKnowledgeRoute: typeof ApiHermesKnowledgeRoute
  ApiHermesNotesRoute: typeof ApiHermesNotesRoute
  ApiHermesOutcomesRoute: typeof ApiHermesOutcomesRoute
  ApiHermesPineScriptAnalysisRoute: typeof ApiHermesPineScriptAnalysisRoute
  ApiHermesRequestsRoute: typeof ApiHermesRequestsRoute
  ApiHermesSetupsRoute: typeof ApiHermesSetupsRoute
  ApiHermesSmcChatRoute: typeof ApiHermesSmcChatRoute
  ApiHermesSmcScreenshotsRoute: typeof ApiHermesSmcScreenshotsRoute
  ApiHermesSmcStatusRoute: typeof ApiHermesSmcStatusRoute
  ApiHermesSmcUpgradeChatRoute: typeof ApiHermesSmcUpgradeChatRoute
  ApiHermesSmcUpgradeConfigRoute: typeof ApiHermesSmcUpgradeConfigRoute
  ApiHermesStrategyAnalysisRoute: typeof ApiHermesStrategyAnalysisRoute
  ApiHermesStrategyRulesRoute: typeof ApiHermesStrategyRulesRoute
  ApiHermesUnderstandingRoute: typeof ApiHermesUnderstandingRoute
  ApiHermesUserStrategiesRoute: typeof ApiHermesUserStrategiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hermes': {
      id: '/hermes'
      path: '/hermes'
      fullPath: '/hermes'
      preLoaderRoute: typeof HermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnl': {
      id: '/pnl'
      path: '/pnl'
      fullPath: '/pnl'
      preLoaderRoute: typeof PnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smc': {
      id: '/smc'
      path: '/smc'
      fullPath: '/smc'
      preLoaderRoute: typeof SmcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validator': {
      id: '/validator'
      path: '/validator'
      fullPath: '/validator'
      preLoaderRoute: typeof ValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/economic-events': {
      id: '/api/economic-events'
      path: '/api/economic-events'
      fullPath: '/api/economic-events'
      preLoaderRoute: typeof ApiEconomicEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finnhub_webhook': {
      id: '/api/finnhub_webhook'
      path: '/api/finnhub_webhook'
      fullPath: '/api/finnhub_webhook'
      preLoaderRoute: typeof ApiFinnhub_webhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ohlcv': {
      id: '/api/ohlcv'
      path: '/api/ohlcv'
      fullPath: '/api/ohlcv'
      preLoaderRoute: typeof ApiOhlcvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smc': {
      id: '/api/smc'
      path: '/api/smc'
      fullPath: '/api/smc'
      preLoaderRoute: typeof ApiSmcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smc-analyze': {
      id: '/api/smc-analyze'
      path: '/api/smc-analyze'
      fullPath: '/api/smc-analyze'
      preLoaderRoute: typeof ApiSmcAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smc-migrate': {
      id: '/api/smc-migrate'
      path: '/api/smc-migrate'
      fullPath: '/api/smc-migrate'
      preLoaderRoute: typeof ApiSmcMigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smc-migrate-chat': {
      id: '/api/smc-migrate-chat'
      path: '/api/smc-migrate-chat'
      fullPath: '/api/smc-migrate-chat'
      preLoaderRoute: typeof ApiSmcMigrateChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smc-strategy-config': {
      id: '/api/smc-strategy-config'
      path: '/api/smc-strategy-config'
      fullPath: '/api/smc-strategy-config'
      preLoaderRoute: typeof ApiSmcStrategyConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strategies': {
      id: '/api/strategies'
      path: '/api/strategies'
      fullPath: '/api/strategies'
      preLoaderRoute: typeof ApiStrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/_debug': {
      id: '/api/hermes/_debug'
      path: '/api/hermes'
      fullPath: '/api/hermes'
      preLoaderRoute: typeof ApiHermesDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/accounts': {
      id: '/api/hermes/accounts'
      path: '/api/hermes/accounts'
      fullPath: '/api/hermes/accounts'
      preLoaderRoute: typeof ApiHermesAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/analysis': {
      id: '/api/hermes/analysis'
      path: '/api/hermes/analysis'
      fullPath: '/api/hermes/analysis'
      preLoaderRoute: typeof ApiHermesAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/analyze-news': {
      id: '/api/hermes/analyze-news'
      path: '/api/hermes/analyze-news'
      fullPath: '/api/hermes/analyze-news'
      preLoaderRoute: typeof ApiHermesAnalyzeNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/analyze-with-hermes': {
      id: '/api/hermes/analyze-with-hermes'
      path: '/api/hermes/analyze-with-hermes'
      fullPath: '/api/hermes/analyze-with-hermes'
      preLoaderRoute: typeof ApiHermesAnalyzeWithHermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/backtests': {
      id: '/api/hermes/backtests'
      path: '/api/hermes/backtests'
      fullPath: '/api/hermes/backtests'
      preLoaderRoute: typeof ApiHermesBacktestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/journal': {
      id: '/api/hermes/journal'
      path: '/api/hermes/journal'
      fullPath: '/api/hermes/journal'
      preLoaderRoute: typeof ApiHermesJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/knowledge': {
      id: '/api/hermes/knowledge'
      path: '/api/hermes/knowledge'
      fullPath: '/api/hermes/knowledge'
      preLoaderRoute: typeof ApiHermesKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/notes': {
      id: '/api/hermes/notes'
      path: '/api/hermes/notes'
      fullPath: '/api/hermes/notes'
      preLoaderRoute: typeof ApiHermesNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/outcomes': {
      id: '/api/hermes/outcomes'
      path: '/api/hermes/outcomes'
      fullPath: '/api/hermes/outcomes'
      preLoaderRoute: typeof ApiHermesOutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/pine-script-analysis': {
      id: '/api/hermes/pine-script-analysis'
      path: '/api/hermes/pine-script-analysis'
      fullPath: '/api/hermes/pine-script-analysis'
      preLoaderRoute: typeof ApiHermesPineScriptAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/requests': {
      id: '/api/hermes/requests'
      path: '/api/hermes/requests'
      fullPath: '/api/hermes/requests'
      preLoaderRoute: typeof ApiHermesRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/setups': {
      id: '/api/hermes/setups'
      path: '/api/hermes/setups'
      fullPath: '/api/hermes/setups'
      preLoaderRoute: typeof ApiHermesSetupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/smc-chat': {
      id: '/api/hermes/smc-chat'
      path: '/api/hermes/smc-chat'
      fullPath: '/api/hermes/smc-chat'
      preLoaderRoute: typeof ApiHermesSmcChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/smc-screenshots': {
      id: '/api/hermes/smc-screenshots'
      path: '/api/hermes/smc-screenshots'
      fullPath: '/api/hermes/smc-screenshots'
      preLoaderRoute: typeof ApiHermesSmcScreenshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/smc-status': {
      id: '/api/hermes/smc-status'
      path: '/api/hermes/smc-status'
      fullPath: '/api/hermes/smc-status'
      preLoaderRoute: typeof ApiHermesSmcStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/smc-upgrade-chat': {
      id: '/api/hermes/smc-upgrade-chat'
      path: '/api/hermes/smc-upgrade-chat'
      fullPath: '/api/hermes/smc-upgrade-chat'
      preLoaderRoute: typeof ApiHermesSmcUpgradeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/smc-upgrade-config': {
      id: '/api/hermes/smc-upgrade-config'
      path: '/api/hermes/smc-upgrade-config'
      fullPath: '/api/hermes/smc-upgrade-config'
      preLoaderRoute: typeof ApiHermesSmcUpgradeConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/strategy-analysis': {
      id: '/api/hermes/strategy-analysis'
      path: '/api/hermes/strategy-analysis'
      fullPath: '/api/hermes/strategy-analysis'
      preLoaderRoute: typeof ApiHermesStrategyAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/strategy-rules': {
      id: '/api/hermes/strategy-rules'
      path: '/api/hermes/strategy-rules'
      fullPath: '/api/hermes/strategy-rules'
      preLoaderRoute: typeof ApiHermesStrategyRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/understanding': {
      id: '/api/hermes/understanding'
      path: '/api/hermes/understanding'
      fullPath: '/api/hermes/understanding'
      preLoaderRoute: typeof ApiHermesUnderstandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/user-strategies': {
      id: '/api/hermes/user-strategies'
      path: '/api/hermes/user-strategies'
      fullPath: '/api/hermes/user-strategies'
      preLoaderRoute: typeof ApiHermesUserStrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  BacktestRoute: BacktestRoute,
  BriefingRoute: BriefingRoute,
  CalendarRoute: CalendarRoute,
  ConsoleRoute: ConsoleRoute,
  HelpRoute: HelpRoute,
  HermesRoute: HermesRoute,
  JournalRoute: JournalRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  PnlRoute: PnlRoute,
  SettingsRoute: SettingsRoute,
  SmcRoute: SmcRoute,
  ValidatorRoute: ValidatorRoute,
  ApiEconomicEventsRoute: ApiEconomicEventsRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiFinnhub_webhookRoute: ApiFinnhub_webhookRoute,
  ApiOhlcvRoute: ApiOhlcvRoute,
  ApiSmcRoute: ApiSmcRoute,
  ApiSmcAnalyzeRoute: ApiSmcAnalyzeRoute,
  ApiSmcMigrateRoute: ApiSmcMigrateRoute,
  ApiSmcMigrateChatRoute: ApiSmcMigrateChatRoute,
  ApiSmcStrategyConfigRoute: ApiSmcStrategyConfigRoute,
  ApiStrategiesRoute: ApiStrategiesRoute,
  ApiHermesDebugRoute: ApiHermesDebugRoute,
  ApiHermesAccountsRoute: ApiHermesAccountsRoute,
  ApiHermesAnalysisRoute: ApiHermesAnalysisRoute,
  ApiHermesAnalyzeNewsRoute: ApiHermesAnalyzeNewsRoute,
  ApiHermesAnalyzeWithHermesRoute: ApiHermesAnalyzeWithHermesRoute,
  ApiHermesBacktestsRoute: ApiHermesBacktestsRoute,
  ApiHermesJournalRoute: ApiHermesJournalRoute,
  ApiHermesKnowledgeRoute: ApiHermesKnowledgeRoute,
  ApiHermesNotesRoute: ApiHermesNotesRoute,
  ApiHermesOutcomesRoute: ApiHermesOutcomesRoute,
  ApiHermesPineScriptAnalysisRoute: ApiHermesPineScriptAnalysisRoute,
  ApiHermesRequestsRoute: ApiHermesRequestsRoute,
  ApiHermesSetupsRoute: ApiHermesSetupsRoute,
  ApiHermesSmcChatRoute: ApiHermesSmcChatRoute,
  ApiHermesSmcScreenshotsRoute: ApiHermesSmcScreenshotsRoute,
  ApiHermesSmcStatusRoute: ApiHermesSmcStatusRoute,
  ApiHermesSmcUpgradeChatRoute: ApiHermesSmcUpgradeChatRoute,
  ApiHermesSmcUpgradeConfigRoute: ApiHermesSmcUpgradeConfigRoute,
  ApiHermesStrategyAnalysisRoute: ApiHermesStrategyAnalysisRoute,
  ApiHermesStrategyRulesRoute: ApiHermesStrategyRulesRoute,
  ApiHermesUnderstandingRoute: ApiHermesUnderstandingRoute,
  ApiHermesUserStrategiesRoute: ApiHermesUserStrategiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
