/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as HermesRouteImport } from './routes/hermes'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SmcRouteImport } from './routes/smc'
import { Route as ValidatorRouteImport } from './routes/validator'
import { Route as ApiEconomicEventsRouteImport } from './routes/api/economic-events'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiFinnhub_webhookRouteImport } from './routes/api/finnhub_webhook'
import { Route as ApiOhlcvRouteImport } from './routes/api/ohlcv'
import { Route as ApiSmcRouteImport } from './routes/api/smc'
import { Route as ApiHermesDebugRouteImport } from './routes/api/hermes/_debug'
import { Route as ApiHermesAccountsRouteImport } from './routes/api/hermes/accounts'
import { Route as ApiHermesAnalysisRouteImport } from './routes/api/hermes/analysis'
import { Route as ApiHermesBacktestsRouteImport } from './routes/api/hermes/backtests'
import { Route as ApiHermesJournalRouteImport } from './routes/api/hermes/journal'
import { Route as ApiHermesKnowledgeRouteImport } from './routes/api/hermes/knowledge'
import { Route as ApiHermesNotesRouteImport } from './routes/api/hermes/notes'
import { Route as ApiHermesRequestsRouteImport } from './routes/api/hermes/requests'
import { Route as ApiHermesSetupsRouteImport } from './routes/api/hermes/setups'
import { Route as ApiHermesStrategyRulesRouteImport } from './routes/api/hermes/strategy-rules'
import { Route as ApiHermesUnderstandingRouteImport } from './routes/api/hermes/understanding'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const HermesRoute = HermesRouteImport.update({
  id: '/hermes',
  path: '/hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SmcRoute = SmcRouteImport.update({
  id: '/smc',
  path: '/smc',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidatorRoute = ValidatorRouteImport.update({
  id: '/validator',
  path: '/validator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEconomicEventsRoute = ApiEconomicEventsRouteImport.update({
  id: '/api/economic-events',
  path: '/api/economic-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinnhub_webhookRoute = ApiFinnhub_webhookRouteImport.update({
  id: '/api/finnhub_webhook',
  path: '/api/finnhub_webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOhlcvRoute = ApiOhlcvRouteImport.update({
  id: '/api/ohlcv',
  path: '/api/ohlcv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmcRoute = ApiSmcRouteImport.update({
  id: '/api/smc',
  path: '/api/smc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesDebugRoute = ApiHermesDebugRouteImport.update({
  id: '/api/hermes/_debug',
  path: '/api/hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesAccountsRoute = ApiHermesAccountsRouteImport.update({
  id: '/api/hermes/accounts',
  path: '/api/hermes/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesAnalysisRoute = ApiHermesAnalysisRouteImport.update({
  id: '/api/hermes/analysis',
  path: '/api/hermes/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesBacktestsRoute = ApiHermesBacktestsRouteImport.update({
  id: '/api/hermes/backtests',
  path: '/api/hermes/backtests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesJournalRoute = ApiHermesJournalRouteImport.update({
  id: '/api/hermes/journal',
  path: '/api/hermes/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesKnowledgeRoute = ApiHermesKnowledgeRouteImport.update({
  id: '/api/hermes/knowledge',
  path: '/api/hermes/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesNotesRoute = ApiHermesNotesRouteImport.update({
  id: '/api/hermes/notes',
  path: '/api/hermes/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesRequestsRoute = ApiHermesRequestsRouteImport.update({
  id: '/api/hermes/requests',
  path: '/api/hermes/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesSetupsRoute = ApiHermesSetupsRouteImport.update({
  id: '/api/hermes/setups',
  path: '/api/hermes/setups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesStrategyRulesRoute = ApiHermesStrategyRulesRouteImport.update({
  id: '/api/hermes/strategy-rules',
  path: '/api/hermes/strategy-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesUnderstandingRoute = ApiHermesUnderstandingRouteImport.update({
  id: '/api/hermes/understanding',
  path: '/api/hermes/understanding',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/backtest': typeof BacktestRoute
  '/calendar': typeof CalendarRoute
  '/console': typeof ConsoleRoute
  '/hermes': typeof HermesRoute
  '/journal': typeof JournalRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/smc': typeof SmcRoute
  '/validator': typeof ValidatorRoute
  '/api/economic-events': typeof ApiEconomicEventsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/finnhub_webhook': typeof ApiFinnhub_webhookRoute
  '/api/ohlcv': typeof ApiOhlcvRoute
  '/api/smc': typeof ApiSmcRoute
  '/api/hermes': typeof ApiHermesDebugRoute
  '/api/hermes/accounts': typeof ApiHermesAccountsRoute
  '/api/hermes/analysis': typeof ApiHermesAnalysisRoute
  '/api/hermes/backtests': typeof ApiHermesBacktestsRoute
  '/api/hermes/journal': typeof ApiHermesJournalRoute
  '/api/hermes/knowledge': typeof ApiHermesKnowledgeRoute
  '/api/hermes/notes': typeof ApiHermesNotesRoute
  '/api/hermes/requests': typeof ApiHermesRequestsRoute
  '/api/hermes/setups': typeof ApiHermesSetupsRoute
  '/api/hermes/strategy-rules': typeof ApiHermesStrategyRulesRoute
  '/api/hermes/understanding': typeof ApiHermesUnderstandingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/backtest': typeof BacktestRoute
  '/calendar': typeof CalendarRoute
  '/console': typeof ConsoleRoute
  '/hermes': typeof HermesRoute
  '/journal': typeof JournalRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/smc': typeof SmcRoute
  '/validator': typeof ValidatorRoute
  '/api/economic-events': typeof ApiEconomicEventsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/finnhub_webhook': typeof ApiFinnhub_webhookRoute
  '/api/ohlcv': typeof ApiOhlcvRoute
  '/api/smc': typeof ApiSmcRoute
  '/api/hermes': typeof ApiHermesDebugRoute
  '/api/hermes/accounts': typeof ApiHermesAccountsRoute
  '/api/hermes/analysis': typeof ApiHermesAnalysisRoute
  '/api/hermes/backtests': typeof ApiHermesBacktestsRoute
  '/api/hermes/journal': typeof ApiHermesJournalRoute
  '/api/hermes/knowledge': typeof ApiHermesKnowledgeRoute
  '/api/hermes/notes': typeof ApiHermesNotesRoute
  '/api/hermes/requests': typeof ApiHermesRequestsRoute
  '/api/hermes/setups': typeof ApiHermesSetupsRoute
  '/api/hermes/strategy-rules': typeof ApiHermesStrategyRulesRoute
  '/api/hermes/understanding': typeof ApiHermesUnderstandingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/backtest': typeof BacktestRoute
  '/calendar': typeof CalendarRoute
  '/console': typeof ConsoleRoute
  '/hermes': typeof HermesRoute
  '/journal': typeof JournalRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/smc': typeof SmcRoute
  '/validator': typeof ValidatorRoute
  '/api/economic-events': typeof ApiEconomicEventsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/finnhub_webhook': typeof ApiFinnhub_webhookRoute
  '/api/ohlcv': typeof ApiOhlcvRoute
  '/api/smc': typeof ApiSmcRoute
  '/api/hermes/_debug': typeof ApiHermesDebugRoute
  '/api/hermes/accounts': typeof ApiHermesAccountsRoute
  '/api/hermes/analysis': typeof ApiHermesAnalysisRoute
  '/api/hermes/backtests': typeof ApiHermesBacktestsRoute
  '/api/hermes/journal': typeof ApiHermesJournalRoute
  '/api/hermes/knowledge': typeof ApiHermesKnowledgeRoute
  '/api/hermes/notes': typeof ApiHermesNotesRoute
  '/api/hermes/requests': typeof ApiHermesRequestsRoute
  '/api/hermes/setups': typeof ApiHermesSetupsRoute
  '/api/hermes/strategy-rules': typeof ApiHermesStrategyRulesRoute
  '/api/hermes/understanding': typeof ApiHermesUnderstandingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/backtest'
    | '/calendar'
    | '/console'
    | '/hermes'
    | '/journal'
    | '/live'
    | '/login'
    | '/settings'
    | '/smc'
    | '/validator'
    | '/api/economic-events'
    | '/api/events'
    | '/api/finnhub_webhook'
    | '/api/ohlcv'
    | '/api/smc'
    | '/api/hermes'
    | '/api/hermes/accounts'
    | '/api/hermes/analysis'
    | '/api/hermes/backtests'
    | '/api/hermes/journal'
    | '/api/hermes/knowledge'
    | '/api/hermes/notes'
    | '/api/hermes/requests'
    | '/api/hermes/setups'
    | '/api/hermes/strategy-rules'
    | '/api/hermes/understanding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/backtest'
    | '/calendar'
    | '/console'
    | '/hermes'
    | '/journal'
    | '/live'
    | '/login'
    | '/settings'
    | '/smc'
    | '/validator'
    | '/api/economic-events'
    | '/api/events'
    | '/api/finnhub_webhook'
    | '/api/ohlcv'
    | '/api/smc'
    | '/api/hermes'
    | '/api/hermes/accounts'
    | '/api/hermes/analysis'
    | '/api/hermes/backtests'
    | '/api/hermes/journal'
    | '/api/hermes/knowledge'
    | '/api/hermes/notes'
    | '/api/hermes/requests'
    | '/api/hermes/setups'
    | '/api/hermes/strategy-rules'
    | '/api/hermes/understanding'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/backtest'
    | '/calendar'
    | '/console'
    | '/hermes'
    | '/journal'
    | '/live'
    | '/login'
    | '/settings'
    | '/smc'
    | '/validator'
    | '/api/economic-events'
    | '/api/events'
    | '/api/finnhub_webhook'
    | '/api/ohlcv'
    | '/api/smc'
    | '/api/hermes/_debug'
    | '/api/hermes/accounts'
    | '/api/hermes/analysis'
    | '/api/hermes/backtests'
    | '/api/hermes/journal'
    | '/api/hermes/knowledge'
    | '/api/hermes/notes'
    | '/api/hermes/requests'
    | '/api/hermes/setups'
    | '/api/hermes/strategy-rules'
    | '/api/hermes/understanding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  BacktestRoute: typeof BacktestRoute
  CalendarRoute: typeof CalendarRoute
  ConsoleRoute: typeof ConsoleRoute
  HermesRoute: typeof HermesRoute
  JournalRoute: typeof JournalRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SmcRoute: typeof SmcRoute
  ValidatorRoute: typeof ValidatorRoute
  ApiEconomicEventsRoute: typeof ApiEconomicEventsRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiFinnhub_webhookRoute: typeof ApiFinnhub_webhookRoute
  ApiOhlcvRoute: typeof ApiOhlcvRoute
  ApiSmcRoute: typeof ApiSmcRoute
  ApiHermesDebugRoute: typeof ApiHermesDebugRoute
  ApiHermesAccountsRoute: typeof ApiHermesAccountsRoute
  ApiHermesAnalysisRoute: typeof ApiHermesAnalysisRoute
  ApiHermesBacktestsRoute: typeof ApiHermesBacktestsRoute
  ApiHermesJournalRoute: typeof ApiHermesJournalRoute
  ApiHermesKnowledgeRoute: typeof ApiHermesKnowledgeRoute
  ApiHermesNotesRoute: typeof ApiHermesNotesRoute
  ApiHermesRequestsRoute: typeof ApiHermesRequestsRoute
  ApiHermesSetupsRoute: typeof ApiHermesSetupsRoute
  ApiHermesStrategyRulesRoute: typeof ApiHermesStrategyRulesRoute
  ApiHermesUnderstandingRoute: typeof ApiHermesUnderstandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hermes': {
      id: '/hermes'
      path: '/hermes'
      fullPath: '/hermes'
      preLoaderRoute: typeof HermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smc': {
      id: '/smc'
      path: '/smc'
      fullPath: '/smc'
      preLoaderRoute: typeof SmcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validator': {
      id: '/validator'
      path: '/validator'
      fullPath: '/validator'
      preLoaderRoute: typeof ValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/economic-events': {
      id: '/api/economic-events'
      path: '/api/economic-events'
      fullPath: '/api/economic-events'
      preLoaderRoute: typeof ApiEconomicEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finnhub_webhook': {
      id: '/api/finnhub_webhook'
      path: '/api/finnhub_webhook'
      fullPath: '/api/finnhub_webhook'
      preLoaderRoute: typeof ApiFinnhub_webhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ohlcv': {
      id: '/api/ohlcv'
      path: '/api/ohlcv'
      fullPath: '/api/ohlcv'
      preLoaderRoute: typeof ApiOhlcvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smc': {
      id: '/api/smc'
      path: '/api/smc'
      fullPath: '/api/smc'
      preLoaderRoute: typeof ApiSmcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/_debug': {
      id: '/api/hermes/_debug'
      path: '/api/hermes'
      fullPath: '/api/hermes'
      preLoaderRoute: typeof ApiHermesDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/accounts': {
      id: '/api/hermes/accounts'
      path: '/api/hermes/accounts'
      fullPath: '/api/hermes/accounts'
      preLoaderRoute: typeof ApiHermesAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/analysis': {
      id: '/api/hermes/analysis'
      path: '/api/hermes/analysis'
      fullPath: '/api/hermes/analysis'
      preLoaderRoute: typeof ApiHermesAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/backtests': {
      id: '/api/hermes/backtests'
      path: '/api/hermes/backtests'
      fullPath: '/api/hermes/backtests'
      preLoaderRoute: typeof ApiHermesBacktestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/journal': {
      id: '/api/hermes/journal'
      path: '/api/hermes/journal'
      fullPath: '/api/hermes/journal'
      preLoaderRoute: typeof ApiHermesJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/knowledge': {
      id: '/api/hermes/knowledge'
      path: '/api/hermes/knowledge'
      fullPath: '/api/hermes/knowledge'
      preLoaderRoute: typeof ApiHermesKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/notes': {
      id: '/api/hermes/notes'
      path: '/api/hermes/notes'
      fullPath: '/api/hermes/notes'
      preLoaderRoute: typeof ApiHermesNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/requests': {
      id: '/api/hermes/requests'
      path: '/api/hermes/requests'
      fullPath: '/api/hermes/requests'
      preLoaderRoute: typeof ApiHermesRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/setups': {
      id: '/api/hermes/setups'
      path: '/api/hermes/setups'
      fullPath: '/api/hermes/setups'
      preLoaderRoute: typeof ApiHermesSetupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/strategy-rules': {
      id: '/api/hermes/strategy-rules'
      path: '/api/hermes/strategy-rules'
      fullPath: '/api/hermes/strategy-rules'
      preLoaderRoute: typeof ApiHermesStrategyRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/understanding': {
      id: '/api/hermes/understanding'
      path: '/api/hermes/understanding'
      fullPath: '/api/hermes/understanding'
      preLoaderRoute: typeof ApiHermesUnderstandingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  BacktestRoute: BacktestRoute,
  CalendarRoute: CalendarRoute,
  ConsoleRoute: ConsoleRoute,
  HermesRoute: HermesRoute,
  JournalRoute: JournalRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SmcRoute: SmcRoute,
  ValidatorRoute: ValidatorRoute,
  ApiEconomicEventsRoute: ApiEconomicEventsRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiFinnhub_webhookRoute: ApiFinnhub_webhookRoute,
  ApiOhlcvRoute: ApiOhlcvRoute,
  ApiSmcRoute: ApiSmcRoute,
  ApiHermesDebugRoute: ApiHermesDebugRoute,
  ApiHermesAccountsRoute: ApiHermesAccountsRoute,
  ApiHermesAnalysisRoute: ApiHermesAnalysisRoute,
  ApiHermesBacktestsRoute: ApiHermesBacktestsRoute,
  ApiHermesJournalRoute: ApiHermesJournalRoute,
  ApiHermesKnowledgeRoute: ApiHermesKnowledgeRoute,
  ApiHermesNotesRoute: ApiHermesNotesRoute,
  ApiHermesRequestsRoute: ApiHermesRequestsRoute,
  ApiHermesSetupsRoute: ApiHermesSetupsRoute,
  ApiHermesStrategyRulesRoute: ApiHermesStrategyRulesRoute,
  ApiHermesUnderstandingRoute: ApiHermesUnderstandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
